[[constraint]]
  branch = "master"
  name = "github.com/Pallinder/go-randomdata"

[[constraint]]
  branch = "master"
  name = "github.com/andreyvit/diff"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  branch = "master"
  name = "github.com/gosuri/uiprogress"

[[constraint]]
  name = "github.com/hetznercloud/hcloud-go"
  version = "1.8.0"

[[constraint]]
  name = "github.com/magiconair/properties"
  version = "1.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
